home:
  route: /
  method: get
  controller: MainController
  action: indexAction

about:
  route: /list
  method: get
  controller: MainController
  action: listAction

display:
  route: /display/{id}
  method: get
  controller: MainController
  action: displayAction

error:
  route: /error
  method: get
  controller: ErrorController
  action: errorAction

showNoId:
  route: /display/
  method: get
  controller: MainController
  action: showNoIdAction

login:
  route: /login
  method: get
  controller: UserController
  action: loginAction

logout:
  route: /logout
  method: get
  controller: UserController
  action: logoutAction
